### ISSUE TITLE
Error when running inference for dataset

### ISSUE THREAD

**Issue by sebastianopazo1** [OpenGVLab/UniHCP#11]
Hi! I was trying to run the inference script for dataset and I obtained the following error.
Traceback (most recent call last):
  File "inference_for_dataset.py", line 51, in <module>
    from core.config import Config 
  File "/home/seba/Documents/UniHCP-inference/core/config.py", line 10, in <module>
    from .utils import printlog
  File "/home/seba/Documents/UniHCP-inference/core/utils.py", line 19, in <module>
    import core.fp16 as fp16
  File "/home/seba/Documents/UniHCP-inference/core/fp16/__init__.py", line 1, in <module>
    from .opt import *
  File "/home/seba/Documents/UniHCP-inference/core/fp16/opt.py", line 8, in <module>
    from .scaler import LossScaler
  File "/home/seba/Documents/UniHCP-inference/core/fp16/scaler.py", line 2, in <module>
    from torch import inf
ImportError: cannot import name 'inf'

Thanks for the help!

**Comment by orashi** [comment]
there are some untested fp16 supports left in the code(due to historical reasons) but are not used for either unihcp training or inference, I'm not sure how this line is invoked, but simply removing all calls invoking that line should be just fine.

**Comment by TaylorLi123** [comment]
I would like to ask how to run the evaluation part of the code, can you share a inference script? Do I need to download all the mentioned datasets? thank you
